name: Deploy To Server

on:
  push:
    branches:
      - main
      
jobs:
  deploy:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_KEY }}
      - name: Deploy commands
        run: |
              echo "Navigating"
              cd ~/qutie/
              echo "Pulling"
              git pull git@github.com:Skektec/qutie.git
              echo "Restarting"
              sudo systemctl restart quoteBot.service
              echo "Notifing"
              node ~/qutie/events/actions/deploymentNotice.js
